baseURL = "http://localhost:1313/"
languageCode = "ja"
title = "Goolge Cloud Platformの導入ならgrasys(グラシス)"
theme = "grasys"

[menu]
# main menu

[[menu.main]]
	name   = "Service"
	url    = "/service"
	weight = 1

[[menu.main]]
	name   = "Case"
	url    = "/case"
	weight = 2

[[menu.main]]
	name   = "Faq"
	url    = "/faq"
	weight = 3

[[menu.main]]
	name   = "Member"
	url    = "/Member"
	weight = 4

[[menu.main]]
	name   = "Recruit"
	url    = "/recruit"
	weight = 5

[[menu.main]]
	name   = "Blog"
	url    = "/blog"
	weight = 6

[[menu.main]]
	name   = "Contact"
	url    = "/contact"
	weight = 7


[params.carousel]
	enable = true

[params.ourservice]
	enable = true
	title = "OUR SERVICE"
	subtitle = "Google Cloud Platform(GCP)の導入から運用、お客様それぞれのニーズに合わせたご要望にもお応えできます。"

[params.case]
	enable = true
	title = "CASE"
	subtitle = "導入事例をご紹介いたします。grasysのサービスをご利用いただいている企業様のお話を伺いました。"

[params.whoweare]
	enable = true
	title = "WHO WE ARE"

[params.recent_posts]
	enable = true
	title = "BLOG"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."